# Generated by Django 5.0.2 on 2024-10-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, verbose_name='Link Unidad Fiscalizable')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Palabras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('palabras', models.CharField(default='Vacio', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Coincidencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documento')),
                ('palabras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.palabras')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo'),
        ),
        migrations.CreateModel(
            name='Unidad_fiscalizable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('expediente', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='unidad_fiscalizable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidad_fiscalizable'),
        ),
    ]
