# Generated by Django 5.0.2 on 2024-10-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odorwatch', '0002_remove_unidadfiscalizable_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='LogsUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
