# Generated by Django 5.0.2 on 2024-11-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odorwatch', '0003_remove_documento_usuario_delete_logsusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadfiscalizable',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
