# Generated by Django 5.0.2 on 2024-11-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odorwatch', '0004_unidadfiscalizable_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadfiscalizable',
            name='codigo',
        ),
    ]
