# Generated by Django 5.0.2 on 2024-11-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odorwatch', '0005_remove_unidadfiscalizable_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadfiscalizable',
            name='año_fecha',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
