# Generated by Django 5.0.2 on 2024-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odorwatch', '0006_unidadfiscalizable_año_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
