# Generated by Django 5.0.2 on 2024-10-30 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='unidadfiscalizable',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='coincidencias',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='coincidencias',
            name='palabras',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='unidad_fiscalizable',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.AddField(
            model_name='logsusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='modulos.usuario'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Coincidencias',
        ),
        migrations.DeleteModel(
            name='Palabras',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='UnidadFiscalizable',
        ),
    ]
