# Generated by Django 5.0.2 on 2024-10-31 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_logsusuario_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_error', models.CharField(max_length=255)),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_error', models.TimeField()),
                ('fecha_error', models.DateField()),
                ('tipo_error', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_error', to='modulos.usuario')),
            ],
        ),
    ]
